// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"database/sql"
	"time"
)

type Expense struct {
	ID                int64          `db:"id" json:"id"`
	Date              time.Time      `db:"date" json:"date"`
	Description       string         `db:"description" json:"description"`
	AmountCents       int64          `db:"amount_cents" json:"amount_cents"`
	PrimaryCategory   string         `db:"primary_category" json:"primary_category"`
	SecondaryCategory string         `db:"secondary_category" json:"secondary_category"`
	Version           int64          `db:"version" json:"version"`
	CreatedAt         sql.NullTime   `db:"created_at" json:"created_at"`
	SyncedAt          interface{}    `db:"synced_at" json:"synced_at"`
	SyncStatus        sql.NullString `db:"sync_status" json:"sync_status"`
}

type Income struct {
	ID          int64          `db:"id" json:"id"`
	Date        time.Time      `db:"date" json:"date"`
	Description string         `db:"description" json:"description"`
	AmountCents int64          `db:"amount_cents" json:"amount_cents"`
	Category    string         `db:"category" json:"category"`
	Version     int64          `db:"version" json:"version"`
	CreatedAt   sql.NullTime   `db:"created_at" json:"created_at"`
	SyncedAt    interface{}    `db:"synced_at" json:"synced_at"`
	SyncStatus  sql.NullString `db:"sync_status" json:"sync_status"`
}

type IncomeCategory struct {
	ID        int64        `db:"id" json:"id"`
	Name      string       `db:"name" json:"name"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
}

type PrimaryCategory struct {
	ID        int64        `db:"id" json:"id"`
	Name      string       `db:"name" json:"name"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
}

type RecurrentExpense struct {
	ID                int64        `db:"id" json:"id"`
	StartDate         time.Time    `db:"start_date" json:"start_date"`
	EndDate           interface{}  `db:"end_date" json:"end_date"`
	RepetitionType    string       `db:"repetition_type" json:"repetition_type"`
	Description       string       `db:"description" json:"description"`
	AmountCents       int64        `db:"amount_cents" json:"amount_cents"`
	PrimaryCategory   string       `db:"primary_category" json:"primary_category"`
	SecondaryCategory string       `db:"secondary_category" json:"secondary_category"`
	IsActive          bool         `db:"is_active" json:"is_active"`
	LastExecutionDate interface{}  `db:"last_execution_date" json:"last_execution_date"`
	CreatedAt         sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt         sql.NullTime `db:"updated_at" json:"updated_at"`
}

type SecondaryCategory struct {
	ID                int64        `db:"id" json:"id"`
	Name              string       `db:"name" json:"name"`
	PrimaryCategoryID int64        `db:"primary_category_id" json:"primary_category_id"`
	CreatedAt         sql.NullTime `db:"created_at" json:"created_at"`
}

type SyncQueue struct {
	ID                 int64       `db:"id" json:"id"`
	Operation          string      `db:"operation" json:"operation"`
	ExpenseID          int64       `db:"expense_id" json:"expense_id"`
	ExpenseDay         interface{} `db:"expense_day" json:"expense_day"`
	ExpenseMonth       interface{} `db:"expense_month" json:"expense_month"`
	ExpenseDescription interface{} `db:"expense_description" json:"expense_description"`
	ExpenseAmountCents interface{} `db:"expense_amount_cents" json:"expense_amount_cents"`
	ExpensePrimary     interface{} `db:"expense_primary" json:"expense_primary"`
	ExpenseSecondary   interface{} `db:"expense_secondary" json:"expense_secondary"`
	Status             string      `db:"status" json:"status"`
	Attempts           int64       `db:"attempts" json:"attempts"`
	MaxAttempts        int64       `db:"max_attempts" json:"max_attempts"`
	LastError          interface{} `db:"last_error" json:"last_error"`
	CreatedAt          time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt          time.Time   `db:"updated_at" json:"updated_at"`
	ProcessedAt        interface{} `db:"processed_at" json:"processed_at"`
	NextRetryAt        interface{} `db:"next_retry_at" json:"next_retry_at"`
}
