// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package storage

import (
	"database/sql"
)

type Category struct {
	ID        int64        `db:"id" json:"id"`
	Name      string       `db:"name" json:"name"`
	Type      string       `db:"type" json:"type"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
}

type Expense struct {
	ID                int64          `db:"id" json:"id"`
	Day               int64          `db:"day" json:"day"`
	Month             int64          `db:"month" json:"month"`
	Description       string         `db:"description" json:"description"`
	AmountCents       int64          `db:"amount_cents" json:"amount_cents"`
	PrimaryCategory   string         `db:"primary_category" json:"primary_category"`
	SecondaryCategory string         `db:"secondary_category" json:"secondary_category"`
	Version           int64          `db:"version" json:"version"`
	CreatedAt         sql.NullTime   `db:"created_at" json:"created_at"`
	SyncedAt          interface{}    `db:"synced_at" json:"synced_at"`
	SyncStatus        sql.NullString `db:"sync_status" json:"sync_status"`
}
