// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package storage

import (
	"context"
)

type Querier interface {
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error)
	GetCategorySums(ctx context.Context, month int64) ([]GetCategorySumsRow, error)
	GetExpense(ctx context.Context, id int64) (Expense, error)
	GetExpensesByMonth(ctx context.Context, month int64) ([]Expense, error)
	GetMonthTotal(ctx context.Context, month int64) (int64, error)
	GetPendingSyncExpenses(ctx context.Context, limit int64) ([]GetPendingSyncExpensesRow, error)
	MarkExpenseSyncError(ctx context.Context, id int64) error
	MarkExpenseSynced(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
