-- Add historical expenses (pre-app data)
-- All amounts converted from EUR to cents (multiplied by 100)
-- Set sync_status to 'synced' since these are already in Google Sheets

INSERT INTO expenses (month, day, description, amount_cents, primary_category, secondary_category, sync_status) VALUES
(1, 1, 'Divertimento q1 G', 10000, 'Divertimento', 'Giochi g', 'synced'),
(1, 1, 'Conclave al cinema', 2300, 'Divertimento', 'Divertimento familiare', 'synced'),
(1, 1, 'Spesa 1 gennaio', 5400, 'Spesa', 'Everli', 'synced'),
(1, 1, 'Benzina', 5900, 'Trasporti', 'Spese automobile', 'synced'),
(1, 2, 'Caffettiera da 1', 3000, 'Casa', 'Mobili', 'synced'),
(1, 3, 'Divertimento q1 E', 20000, 'Divertimento', 'Divertimento e', 'synced'),
(1, 6, 'spesa 2 gennaio', 8089, 'Spesa', 'Everli', 'synced'),
(1, 8, 'Commercialista', 21270, 'Tasse e Percentuali', 'Consulting', 'synced'),
(1, 10, 'Elettricità gennaio', 3609, 'Casa', 'Elettricità', 'synced'),
(1, 10, 'Biglietto Brescia', 5200, 'Trasporti', 'Trasporto locale', 'synced'),
(1, 11, 'Fondello per caffettiera', 1400, 'Casa', 'Mobili', 'synced'),
(1, 14, 'Insalata a Brescia', 1150, 'Fuori (come fuori a cena...)', 'Ristoranti', 'synced'),
(1, 14, 'Viaggio Brescia', 1000, 'Trasporti', 'Trasporto locale', 'synced'),
(1, 15, 'Spesa 3 gennaio', 8790, 'Spesa', 'Everli', 'synced'),
(1, 16, 'Parrucchiere e', 3000, 'Salute', 'Personale', 'synced'),
(1, 16, 'Internet gennaio', 4980, 'Casa', 'Internet', 'synced'),
(1, 16, 'Spesa per serata giochi', 2910, 'Spesa', 'Altre spese (non Everli)', 'synced'),
(1, 16, 'Benzina', 6000, 'Trasporti', 'Spese automobile', 'synced'),
(1, 16, 'Psicologo', 5000, 'Salute', 'Dottori', 'synced'),
(1, 24, 'Abbonamento zoom', 1499, 'Altre spese', 'Tech', 'synced'),
(1, 31, 'Ultima spesa gennaio', 11699, 'Spesa', 'Everli', 'synced'),
(1, 31, 'google one', 199, 'Altre spese', 'Tech', 'synced'),
(1, 31, 'icloud+', 199, 'Altre spese', 'Tech', 'synced'),
(1, 31, 'youtube premium', 1300, 'Altre spese', 'Divertimento familiare', 'synced'),
(1, 31, 'tenuta conto', 400, 'Tasse e Percentuali', 'Banche', 'synced'),
(1, 31, 'interessi mutuo gennaio', 64809, 'Casa', 'Mutuo', 'synced'),
(1, 31, 'spese mutuo', 250, 'Tasse e Percentuali', 'Banche', 'synced'),
(2, 3, 'Pagamento aula corso G', 24400, 'Lavoro', 'Lavoro g', 'synced'),
(2, 3, 'Pranzo corso G', 1064, 'Fuori (come fuori a cena...)', 'Cibo a casa', 'synced'),
(2, 3, 'Psicologo e', 5000, 'Salute', 'Dottori', 'synced'),
(2, 5, 'Pagamento Giulia progettazione corso', 16000, 'Lavoro', 'Lavoro g', 'synced'),
(2, 5, 'Telefono e', 599, 'Altre spese', 'Telefono', 'synced'),
(2, 5, 'iCloud', 99, 'Altre spese', 'Tech', 'synced'),
(2, 6, 'Luce febbraio', 3609, 'Casa', 'Elettricità', 'synced'),
(2, 9, 'Cena Verbania', 3900, 'Fuori (come fuori a cena...)', 'Ristoranti', 'synced'),
(2, 9, 'Colazione Verbania', 690, 'Fuori (come fuori a cena...)', 'Ristoranti', 'synced'),
(2, 9, 'Spesa Verbania', 1680, 'Fuori (come fuori a cena...)', 'Altre spese (non Everli)', 'synced'),
(2, 10, 'Benzina', 6300, 'Trasporti', 'Spese automobile', 'synced'),
(2, 11, 'Spesa febbraio 2', 11900, 'Spesa', 'Everli', 'synced'),
(2, 12, 'Cinema bob Dylan', 2200, 'Divertimento', 'Divertimento familiare', 'synced'),
(2, 12, 'Vodafone febbraio', 2490, 'Casa', 'Telefono', 'synced'),
(2, 13, 'iCloud febbraio', 99, 'Altre spese', 'Tech', 'synced'),
(2, 13, 'KVM', 16500, 'Divertimento', 'Learning e', 'synced'),
(2, 14, 'Freccia rossa brescia', 5200, 'Trasporti', 'Trasporto locale', 'synced'),
(2, 15, 'Home assistant green', 4400, 'Casa', 'Tech', 'synced'),
(2, 15, 'Prima rata ordinaria', 40459, 'Casa', 'Spese condominiali', 'synced'),
(2, 18, 'Trenord brescia', 600, 'Trasporti', 'Trasporto locale', 'synced'),
(2, 21, 'Assicurazione auto G', 58018, 'Trasporti', 'Spese automobile', 'synced'),
(2, 21, 'Spesa per casa', 1864, 'Spesa', 'Altre spese (non Everli)', 'synced'),
(2, 21, 'Pillola 3 mesi', 4442, 'Salute', 'Medicine', 'synced'),
(2, 21, 'Tovaglioli e spazzolino', 948, 'Spesa', 'Altre spese (non Everli)', 'synced'),
(2, 22, 'Benzina G', 4911, 'Trasporti', 'Spese automobile', 'synced'),
(2, 22, 'Terme', 22660, 'Divertimento', 'Divertimento familiare', 'synced'),
(2, 23, 'Porta cellulare auto', 2300, 'Trasporti', 'Spese automobile', 'synced'),
(2, 24, 'Psicologo E', 5000, 'Salute', 'Dottori', 'synced'),
(2, 25, 'Spesa', 12300, 'Spesa', 'Everli', 'synced'),
(2, 27, 'Viaggio Brescia marzo', 4380, 'Trasporti', 'Trasporto locale', 'synced'),
(3, 4, 'Termostato smart', 15900, 'Casa', 'Tech', 'synced'),
(3, 5, 'Eversli spesa', 12694, 'Spesa', 'Everli', 'synced'),
(3, 5, 'Scatola elettrica', 1000, 'Casa', 'Tech', 'synced'),
(3, 6, 'Energia marzo', 3690, 'Casa', 'Elettricità', 'synced'),
(3, 6, 'Benzina G', 6101, 'Trasporti', 'Spese automobile', 'synced'),
(3, 10, 'Psicologo e', 5000, 'Salute', 'Dottori', 'synced'),
(3, 12, 'Spesa marzo', 9400, 'Spesa', 'Everli', 'synced'),
(3, 12, 'Telefono marzo', 2500, 'Casa', 'Internet', 'synced'),
(3, 13, 'iCloud', 99, 'Altre spese', 'Tech', 'synced'),
(3, 17, 'Bilancia cucina', 3235, 'Casa', 'Mobili', 'synced'),
(3, 17, 'Preservativi', 4265, 'Salute', 'Medicine', 'synced'),
(3, 17, 'Psicologo', 5000, 'Salute', 'Dottori', 'synced'),
(3, 20, 'Benzina', 6003, 'Trasporti', 'Spese automobile', 'synced'),
(3, 24, 'iCloud', 99, 'Altre spese', 'Tech', 'synced'),
(3, 24, 'mutuo marzo', 58394, 'Casa', 'Mutuo', 'synced'),
(3, 25, 'Psicologo e', 4900, 'Salute', 'Dottori', 'synced'),
(3, 25, 'telefono g', 1000, 'Altre spese', 'Tech', 'synced'),
(3, 25, 'telefono e', 600, 'Altre spese', 'Tech', 'synced'),
(3, 25, 'Spese condominiali rata#3', 32335, 'Casa', 'Spese condominiali', 'synced'),
(3, 26, 'Benzina', 6200, 'Trasporti', 'Spese automobile', 'synced'),
(3, 31, 'Benzina', 5701, 'Trasporti', 'Spese automobile', 'synced'),
(4, 2, 'Divertimento q2', 30000, 'Divertimento', 'Divertimento familiare', 'synced'),
(4, 4, 'Commercialista', 14560, 'Tasse e Percentuali', 'Consulting', 'synced'),
(4, 4, 'iliad e', 599, 'Altre spese', 'Tech', 'synced'),
(4, 5, 'Mozzarella e lievito', 852, 'Spesa', 'Altre spese (non Everli)', 'synced'),
(4, 6, 'Balcone primavera', 10550, 'Casa', 'Mobili', 'synced'),
(4, 8, 'Psicologo e', 4900, 'Salute', 'Dottori', 'synced'),
(4, 8, 'Everli', 7400, 'Spesa', 'Everli', 'synced'),
(4, 11, 'Benzina', 5586, 'Trasporti', 'Spese automobile', 'synced'),
(4, 11, 'Birra, patatine e dentifricio', 856, 'Spesa', 'Altre spese (non Everli)', 'synced'),
(4, 20, 'Spesa Everli', 11000, 'Spesa', 'Everli', 'synced'),
(4, 24, 'mutuo aprile', 56865, 'Casa', 'Mutuo', 'synced'),
(4, 29, 'Pillola', 6731, 'Salute', 'Medicine', 'synced'),
(4, 30, 'Palestra 13 mesi', 27880, 'Salute', 'Sport', 'synced'),
(5, 4, 'Psicologo e', 5000, 'Salute', 'Dottori', 'synced'),
(5, 4, 'Iliad e', 600, 'Altre spese', 'Tech', 'synced'),
(5, 4, 'Phon', 3300, 'Casa', 'Tech', 'synced'),
(5, 6, 'gomme', 4000, 'Trasporti', 'Spese automobile', 'synced'),
(5, 7, 'Spesa maggio', 11600, 'Spesa', 'Everli', 'synced'),
(5, 7, 'viaggio company meeting', 11300, 'Trasporti', 'Trasporto locale', 'synced'),
(5, 7, 'Visita Cheratocono', 10200, 'Salute', 'Dottori', 'synced'),
(5, 9, 'Parrucchiere e', 3000, 'Salute', 'Personale', 'synced'),
(5, 13, 'Internet', 2490, 'Casa', 'Internet', 'synced'),
(5, 13, 'Patreon Sly flourish', 366, 'Divertimento', 'Learning e', 'synced'),
(5, 14, 'Cena conclusiva sdv', 8000, 'Fuori (come fuori a cena...)', 'Ristoranti', 'synced'),
(5, 14, 'Benzina', 6400, 'Trasporti', 'Spese automobile', 'synced'),
(5, 16, 'Regalo mis3', 9800, 'Divertimento', 'Altri regali', 'synced'),
(5, 16, 'Spesa Gigante', 3708, 'Spesa', 'Altre spese (non Everli)', 'synced'),
(5, 16, 'Mascherine', 1196, 'Salute', 'Altre spese (non Everli)', 'synced'),
(5, 16, 'Calze compressione', 1099, 'Salute', 'Altre spese (non Everli)', 'synced'),
(5, 17, 'Revisione', 9000, 'Trasporti', 'Spese automobile', 'synced'),
(5, 19, '(13822 e 13788) es ORDINARIA 2024/2025 (Rata n. 4)', 32335, 'Casa', 'Spese condominiali', 'synced'),
(5, 19, 'Psicologo e tutto maggio', 10000, 'Salute', 'Dottori', 'synced'),
(5, 19, 'spese condominiali rata#4', 32335, 'Casa', 'Spese condominiali', 'synced'),
(5, 21, 'Kit emergenza', 12000, 'Salute', 'Altre spese (non Everli)', 'synced'),
(5, 23, 'Dentifricio e carta pacchi', 1400, 'Spesa', 'Altre spese (non Everli)', 'synced'),
(5, 24, 'Apple bill', 99, 'Casa', 'Tech', 'synced'),
(5, 25, 'Crema e würstel', 3000, 'Spesa', 'Altre spese (non Everli)', 'synced'),
(5, 27, 'Bici g', 6000, 'Trasporti', 'Trasporto locale', 'synced'),
(5, 27, 'Scarpe e', 8000, 'Vestiti', 'Vacanza estiva', 'synced'),
(5, 28, 'Ali a dal YouTube', 6000, 'Divertimento', 'Learning e', 'synced'),
(6, 18, 'Epidemic sound anno 2', 36558, 'Altre spese', '2DM', 'synced'),
(6, 18, 'Rinnovo dominio duedraghialmicrofono.com', 2195, 'Altre spese', '2DM', 'synced'),
(6, 19, 'Passaggio ad iliad', 4000, 'Casa', 'Internet', 'synced'),
(6, 20, 'Freccia rossa brescia', 5200, 'Trasporti', 'Trasporto locale', 'synced'),
(6, 20, 'viaggio in giappone', 165200, 'Viaggi', 'Vacanza estiva', 'synced'),
(6, 22, 'Benzina', 5500, 'Trasporti', 'Spese automobile', 'synced'),
(6, 26, 'topografia cheratocono', 10200, 'Salute', 'Dottori', 'synced'),
(6, 26, 'divertimento q2', 60000, 'Divertimento', 'Divertimento familiare', 'synced'),
(6, 27, 'Spesa', 12800, 'Spesa', 'Everli', 'synced'),
(6, 30, 'Benzina', 6400, 'Trasporti', 'Spese automobile', 'synced'),
(7, 3, 'Trimestre commercialista', 14560, 'Tasse e Percentuali', 'Altre tasse e percentuali', 'synced'),
(7, 4, 'Everli sub', 9999, 'Spesa', 'Everli', 'synced'),
(7, 4, 'Spesa', 10000, 'Spesa', 'Everli', 'synced'),
(7, 4, 'nen', 7323, 'Casa', 'Elettricità', 'synced'),
(7, 6, 'iCloud', 99, 'Casa', 'Tech', 'synced'),
(7, 7, 'Psicologo e', 5000, 'Salute', 'Dottori', 'synced'),
(7, 8, 'Organizzatori per libreria e lenti a contatto', 5600, 'Casa', 'Mobili', 'synced'),
(7, 9, 'Spese per casa', 10000, 'Casa', 'Mobili', 'synced'),
(7, 11, 'iCloud', 99, 'Casa', 'Tech', 'synced'),
(7, 12, 'spese condominiali rata#5', 32335, 'Casa', 'Spese condominiali', 'synced'),
(7, 12, 'Internet Iliad', 2199, 'Casa', 'Internet', 'synced'),
(7, 16, 'Spesa luglio', 7844, 'Spesa', 'Everli', 'synced'),
(7, 17, 'vodafone luglio', 2490, 'Casa', 'Internet', 'synced'),
(7, 20, 'Assicurazione e', 26256, 'Altre spese', 'Assicurazioni', 'synced'),
(7, 20, 'Assicurazione g', 25138, 'Altre spese', 'Assicurazioni', 'synced'),
(7, 21, 'Benzina', 6100, 'Trasporti', 'Spese automobile', 'synced'),
(7, 21, 'Psicologo e', 4900, 'Salute', 'Dottori', 'synced'),
(7, 22, 'Leccarda forno', 3200, 'Casa', 'Mobili', 'synced'),
(7, 22, 'Ciotola acciaio', 1600, 'Casa', 'Mobili', 'synced'),
(7, 24, 'interessi mutuo luglio', 33947, 'Casa', 'Mutuo', 'synced'),
(7, 25, 'Telepass giugno', 1890, 'Trasporti', 'Spese automobile', 'synced'),
(7, 28, 'Psicologo e', 4900, 'Salute', 'Dottori', 'synced'),
(7, 29, 'Cena compleanno e', 6200, 'Spesa', 'Altre spese (non Everli)', 'synced'),
(7, 31, 'Spesa per ospiti e compleanno E', 4109, 'Spesa', 'Altre spese (non Everli)', 'synced'),
(8, 2, 'Benzina', 5558, 'Viaggi', 'Spese automobile', 'synced'),
(8, 3, 'Piatti festa', 1843, 'Spesa', 'Altre spese (non Everli)', 'synced'),
(8, 3, 'Torta è', 5400, 'Spesa', 'Altre spese (non Everli)', 'synced'),
(8, 4, 'Daggerheart', 8900, 'Divertimento', '2DM', 'synced'),
(8, 4, 'Caparra matrimonio', 100000, 'Divertimento', 'Divertimento familiare', 'synced'),
(8, 5, 'iCloud', 99, 'Casa', 'Tech', 'synced'),
(8, 5, 'Luce', 7223, 'Casa', 'Elettricità', 'synced'),
(8, 6, 'Spesa pesto', 1226, 'Spesa', 'Everli', 'synced'),
(8, 8, 'Parcheggio sestri', 1400, 'Trasporti', 'Spese automobile', 'synced'),
(8, 12, 'Internet', 2199, 'Casa', 'Internet', 'synced'),
(8, 18, 'Assicurazione auto rata2', 58051, 'Trasporti', 'Spese automobile', 'synced'),
(8, 20, 'Benzina', 6400, 'Trasporti', 'Spese automobile', 'synced'),
(8, 22, 'Ram', 22500, 'Casa', 'Tech', 'synced'),
(8, 22, 'Spesa + Micheal and grace', 1100, 'Spesa', 'Everli', 'synced'),
(8, 22, 'Vermox', 600, 'Salute', 'Medicine', 'synced'),
(8, 24, 'interessi mutuo agosto', 49579, 'Casa', 'Mutuo', 'synced'),
(8, 25, 'Vietnammonamour', 9500, 'Fuori (come fuori a cena...)', 'Ristoranti', 'synced'),
(8, 27, 'Detergenti (amazon)', 2100, 'Spesa', 'Altre spese (non Everli)', 'synced'),
(8, 27, 'Spesa agosto', 6500, 'Spesa', 'Everli', 'synced'),
(8, 28, '(14389)+(14424) es ORDINARIA 2024/2025 (Rata n. 6)', 32332, 'Casa', 'Spese condominiali', 'synced'),
(8, 28, 'Spesa compleanno Giada', 3237, 'Spesa', 'Altre spese (non Everli)', 'synced'),
(8, 30, 'Claude', 2100, 'Lavoro', 'Tech', 'synced'),
(9, 2, 'Pizza e', 1580, 'Fuori (come fuori a cena...)', 'Cibo a casa', 'synced'),
(9, 3, 'Upgrade claude', 9000, 'Lavoro', 'Tech', 'synced'),
(9, 3, 'Luce', 7323, 'Casa', 'Elettricità', 'synced'),
(9, 5, 'Everli settembre 1', 11597, 'Spesa', 'Everli', 'synced'),
(9, 6, 'iCloud', 99, 'Altre spese', 'Tech', 'synced'),
(9, 6, 'Dragon Delves', 2645, 'Lavoro', '2DM', 'synced'),
(9, 6, 'Telefono e', 998, 'Casa', 'Telefono', 'synced'),
(9, 6, 'Tari 2025 - Rata 1', 5100, 'Casa', 'Tasse statali', 'synced');